name: Build and Deploy to GH Pages
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm install
          npm install -D webpack-cli
          npx webpack --mode production

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with: 
          branch: gh-pages # The branch the action should delpoy to
          folder: dist # The folder the action should deploy
